name: T31
# Build and run tests on Ubuntu

on:
  - push
  - pull_request

jobs:
  build-and-test:
    name: ${{ matrix.os }} tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
      fail-fast: false

    env:
      S2_INSTRUMENT: B
      S2_PROJ: T31
      S2_YEAR: 2021

    steps:
      - uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git gawk findutils python3-gdal
          git clone https://github.com/jhpoelen/zenodo-upload.git
          git clone https://github.com/osgeo/grass.git
          cd grass
          xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
              sudo apt-get install -y --no-install-recommends --no-install-suggests
      - name: Create installation directory
        run: |
          mkdir $HOME/install
      - name: Set number of cores for compilation
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV
      - name: Set LD_LIBRARY_PATH for compilation
        run: |
          echo "LD_LIBRARY_PATH=$HOME/install/lib" >> $GITHUB_ENV
      - name: Build
        working-directory: ./grass
        run: .github/workflows/build_${{ matrix.os }}.sh $HOME/install
      - name: Add the bin directory to PATH
        run: |
          echo "$HOME/install/bin" >> $GITHUB_PATH
      - name: Add Python libs
        working-directory: ./grass
        run: sudo python3 -m pip install --upgrade numpy cf-units thredds_crawler
      - name: Init workflow
        working-directory: .
        run: bash .github/workflows/init.sh
      - name: Run main workflow
        working-directory: .
        run: bash .github/workflows/run.sh
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch
          git pull
          git commit -m "Add changes" scene_lists/*${{ env.S2_PROJ }}*
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true